Qualis
gloggi/qualix pull request #146
Opened 2020-09-29 19:57 UTC by carlobeltrame

Fixes #68, fixes #73

Dieser PR implementiert Qualis. Demo ist auf https://qualix.gloggi.ch deployed.

* [x] Man kann pro Kurs beliebig viele Qualis erstellen.
* [x] Jedes Quali ist mit allen oder nur einigen TN verknüpft.
* [x] Die einzelnen TN im Quali können den Equipenmitgliedern zugeordnet werden.
* [x] Jedes Quali kann beliebig viele der Anforderungen enthalten.
* [x] Im Quali hat man die Möglichkeit, einen Quali-Text zu schreiben, in den man Anforderungen und Beobachtungen einbetten kann.
* [x] Formatierungen im Quali-Text: Für den Moment sind nur normale Textabschnitte und Überschriften aktiviert. In Zukunft können weitere Formatierungen wie Fett, Kursiv, etc. sehr einfach aktiviert werden.
* [x] Anforderungen im Quali können als "erfüllt" oder "nicht erfüllt" markiert werden, oder unbestimmt belassen werden.
* [x] Grosse Teile des Frontends sind jetzt in Vue-Komponenten umgesetzt, um den neuen Rich Text Editor zu unterstützen.
* [x] End-to-end tests mit Cypress für die allerwichtigsten Funktionen wurden hinzugefügt (Login, Registrierung, Einladungen, Beobachtungen erstellen)
* [x] Frontend-Fehler können jetzt auch an Sentry geschickt werden
* [ ] Backend-Tests schreiben

![Screenshot from 2020-09-29 21-42-31](https://user-images.githubusercontent.com/7566995/94607824-baf98300-029c-11eb-9604-3656f87c4478.png)

![Screenshot from 2020-09-29 21-45-00](https://user-images.githubusercontent.com/7566995/94608037-0f046780-029d-11eb-8f84-167ba8d02b9b.png)

2020-10-01 15:34 UTC, davudevren approved these changes
Richtig Sick!
Bin gspannt zum das im Kurs chene iihsetze :))

2020-10-03 09:53 UTC, allanbenelli requested changes
Sehr sehr nice! Danke für den Einsatz @carlobeltrame !
Der Code passt soweit ich es sehe, folgendes ist mir noch aufgefallen beim Testen:

- Beim erstellen neuer Qualis, wenn ich einen Vorlagentext erstellen möchte, dann kommt der Button für den Titel nicht direkt. ich muss dafür irgendwo im Editor Klicken und wieder zurück an die Stelle, dann funktionierts:
![image](https://user-images.githubusercontent.com/17219792/94988502-f088bf80-056d-11eb-9b6e-10d04520609a.png)

- Beim Quali für TN ausfüllen: wenn ich bei einer Mindestanforderung eine Beobachtung auswähle, dann droppt es diese beim Beginn des Editors. Klar kann man diese danach verschieben, jedoch könnte das bei langen schon ausgefüllten Qualis mühsam werden, wenn ich wieder alles hochscrollen muss. ist das Bewusst so?:
![image](https://user-images.githubusercontent.com/17219792/94988526-3ba2d280-056e-11eb-8766-d5dcc54e7e8a.png)

- Ebenfalls beim Quali für TN ausfüllen: Wenn ich auf einem kleinen Browserwindow arbeite (z.b. geteilter Bildschirm) oder auch auf einem Tablet (was ich für im Kurs als realistisch sehe), dann gibt es beim anklicken der Mindestanforderung einen Overflow beim Viewport:
Mit iPad weniger schlimm: 
![image](https://user-images.githubusercontent.com/17219792/94988614-c84d9080-056e-11eb-94f6-166372edf1f2.png)
Auf dem Browser:
![image](https://user-images.githubusercontent.com/17219792/94988638-ffbc3d00-056e-11eb-9717-d5c20ea5e52e.png)

sonst funktioniert alles niquel! echter mehrwert :+1: :)

2020-10-05 06:41 UTC, carlobeltrame commented
@allanbenelli Merci vielmal, sehr gute Punkte. Das erste und dritte habe ich gefixt. Das zweite scheint ein Bug bei Tiptap zu sein, ich muss das noch weiter verfolgen.

2020-10-05 16:46 UTC, manuelmeister commented
Cool!

2020-10-07 10:09 UTC, merged