add freetext to participant
gloggi/qualix pull request #191
Opened 2021-03-23 20:36 UTC by davudevren

Bitte mal reviewe :)

Isch mal e ersti Version (relativ simpel)
Was ich gmacht han:

1. Model und Request ahhpasst
2. Migration erstellt
3. index und edit View gänderet
4. TN-Detail gänderet
5. Controller gänderet, dass mer zrugg zum detail chunnt (wie bim bearbeite von Beobachtige)

-> chend gern ahhpassige ahbringe

2021-03-23 22:13 UTC, carlobeltrame requested changes
Nice! Funktioniert scho voll guet :) D Frag isch no, ob mer de Text au im Quali wür wele aazeige, bin mer aber au grad nöd sicher. Vilicht ischs safer das deet mal wegzlaa und denn hinzuezfüege wenns öpper bruucht. S Druck-Layout vom Quali isch ebe relativ zerbrechlich...

Was mer no fehlt wäred Tests, zumindest für d Validierig. Chönntsch in https://github.com/gloggi/qualix/blob/master/tests/Feature/Admin/Participant/CreateParticipantTest.php und https://github.com/gloggi/qualix/blob/master/tests/Feature/Admin/Participant/UpdateParticipantTest.php ähnlichi Tests wieses z.B. scho für de Scout Name git mache? Und a beidne Orte im `setUp` im `$payload` no en `freetext` ergänze, sodass au testet wird dasses im Normalfall funktioniert.

2021-03-23 22:13 UTC, carlobeltrame commented on resources/views/participant-detail.blade.php
> +                <a href="{{route('admin.participants.edit', ['course' => $course->id, 'participant' => $participant->id])}}">
De Link isch aktuell weg de Margin vom `<p>` no chli wiit une, und chlebt bitz am druf folgende Text. Vilicht chönntsch de Link is `<p>` Tag ine verschiebe, und mit `class="ml-3"` eifach bitz horizontale Abstand zum Text mache?

2021-03-23 22:13 UTC, carlobeltrame commented on resources/views/participant-detail.blade.php
> +                @if (isset($participant->freetext))<p>{{ $participant->freetext }}</p>@endif
Wenn de Text Ziileumbrüch enthaltet werded die bim rendere wege HTML/CSS verschluckt. Das Problem hani bi Beobachtigstext au scho müese löse, chasch eifach d `class="multiline"` uf de `<p>` druf mache, denn sötts funktioniere.

2021-03-24 23:05 UTC, davudevren commented
Isch es so mit de Darstellig besser? 
Und sind die Tests guet?

2021-03-25 09:30 UTC, carlobeltrame commented
Visuell gsehts super uus jetzt! D Tests sind au guet. De Vollständigkeit halber würi no je eine mache wo testet dasses klappt wenn de Freitext gar nöd mitgsendet wird, analog zu `test_shouldValidateNewParticipantData_noScoutName` im CreateParticipantTest und UpdateParticipantTest.

2021-04-05 17:48 UTC, carlobeltrame approved these changes
Merci!

2021-04-05 17:48 UTC, merged