Kontakt Footer & Character Limit
gloggi/qualix pull request #248
Opened 2022-04-05 10:32 UTC by allanbenelli

Fixes #233 and #223

2022-04-06 10:24 UTC, carlobeltrame requested changes
Sieht schon sehr cool aus, merci!

Zwei Einträge im CHANGELOG.md wären noch nice. Vielleicht beim Zeichenlimit so formulieren dass man merkt dass das Limit schon vorher da war, und nur neu sichtbar gemacht wurde? Sonst meint man wir haben das Limit neu eingebaut.

2022-04-06 10:24 UTC, carlobeltrame commented on resources/js/components/CharLimit.vue
> +      <span class="justify-content-center align-self-center d-flex position-absolute w-100">{{this.$t('t.views.observations.char_limit')}} <strong class="ml-1"> {{ this.currentValue.length.toFixed(0)
Ich würde den Text "Zeichen genutzt" einfach weglassen. Wenn man tippt wird einem glaube ich sehr schnell klar was der Counter bedeutet, und so vermeiden wir das Problem, dass "Character" auf Deutsch keine gute gebräuchliche Übersetzung hat.

Wenn dann würde ich eher ein Argumentarium ala #223 in einem `<help-text>` anzeigen.

2022-04-06 10:24 UTC, carlobeltrame commented on resources/views/includes/footer.blade.php
> +    <p class="footer-company-name">{{__('t.footer.slogan')}} - <a href="{{env('APP_CONTACT_LINK', 'mailto:info@qualix.flamberg.ch')}}">{{env('APP_CONTACT_TEXT', __('t.footer.contact_text'))}}</a></p>
Cool dass du einen Fallback hast, falls die Env-Variablen nicht gesetzt sind. Ich könnte mir aber auch vorstellen, dass andere Qualix-Instanzen gar keinen Kontakt angeben möchten. Und für uns wäre es je nach dem auch schwierig, Support für die User einer fremden Qualix-Instanz zu geben, die beliebige Modifikationen haben könnte.
Wie wäre es, wenn der Link nur angezeigt wird, wenn `APP_CONTACT_LINK` nicht leer ist, und im .env.example standardmässig einen leeren Wert eintragen?

2022-04-06 10:24 UTC, carlobeltrame commented on README.md
> +#APP_CONTACT_LINK=mailto:info@qualix.flamberg.ch
Coole Idee dass das `mailto:` direkt im .env eingebaut werden muss. Dann könnte man bei Bedarf stattdessen auch auf ein Formular auf einer Webseite verlinken :+1:

2022-04-06 10:24 UTC, carlobeltrame commented on tests/Feature/App/ReadWelcomePageTest.php
> +        //$response->assertSee(env('APP_CONTACT_TEXT'));
Alten Code entfernen?

2022-04-07 11:50 UTC, allanbenelli commented
@carlobeltrame Danke für das Review, habe deine Vorschläge so angepasst und noch Fix #210 hinzugefügt.

2022-04-07 13:49 UTC, carlobeltrame approved these changes
Super Sache, merci vielmal!

2022-04-07 14:22 UTC, merged