fix: move all env() calls to config
gloggi/qualix pull request #286
Opened 2022-10-01 10:48 UTC by cleverer

This allows to cache the config, as the .env file is not loaded when a cached config exists. See
https://laravel.com/docs/master/configuration#configuration-caching

2022-10-01 10:53 UTC, carlobeltrame requested changes
Nice!

2022-10-01 10:53 UTC, carlobeltrame commented on resources/views/auth/register.blade.php
> +        @if (!empty(config('services.hitobito.client_id')))
Müsste das nicht services.hitobito.base_url sein?

2022-10-01 10:53 UTC, carlobeltrame commented on resources/views/auth/login.blade.php
> +        @if (!empty(config('services.hitobito.client_id')))
Hier ebenfalls..?

2022-10-01 10:58 UTC, cleverer commented on resources/views/auth/register.blade.php
> +        @if (!empty(config('services.hitobito.client_id')))
Das war ursprünglich so, aber die config-variable hat ein default value von demo.hitobito.ch oder so. Das heisst der button wäre immer aktiv.

2022-10-02 15:37 UTC, carlobeltrame requested changes
Ich habe noch rebased, einen inzwischen neu dazugekommenen Aufruf von `env()` ersetzt und die Tests gefixt. Konnte das aber nicht auf deinen Fork pushen, daher siehe mein Branch: https://github.com/gloggi/qualix/tree/allow-config-caching
Die drei Optimierungen funktionieren auf dem Deployment qualix.gryfensee.ch super jetzt.
Wenn du möchtest (fürs Hacktoberfest) kannst du deinen Branch auf meinen resetten, dann kann ich den PR annehmen. Ansonsten würde ich dann irgendwann nächstens mal meinen Branch in master mergen und den PR hier schliessen.

2022-10-03 09:07 UTC, cleverer commented
> Ich habe noch rebased, einen inzwischen neu dazugekommenen Aufruf von `env()` ersetzt und die Tests gefixt. Konnte das aber nicht auf deinen Fork pushen, daher siehe mein Branch: https://github.com/gloggi/qualix/tree/allow-config-caching
> Die drei Optimierungen funktionieren auf dem Deployment qualix.gryfensee.ch super jetzt.
> Wenn du möchtest (fürs Hacktoberfest) kannst du deinen Branch auf meinen resetten, dann kann ich den PR annehmen. Ansonsten würde ich dann irgendwann nächstens mal meinen Branch in master mergen und den PR hier schliessen.

Hab deine changes cherry-picked (ohne die sentry-changes ;) ) und hier gepusht… merci für das saubere review!

2022-10-03 09:45 UTC, carlobeltrame approved these changes

2022-10-03 09:45 UTC, carlobeltrame commented
Merci vielmal!

2022-10-03 09:45 UTC, merged